sudo: false

language: ruby
rvm:
  - 2.6.3
node_js:
  - "10"

cache:
  directories:
    - node_modules

script:
  - jekyll build

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master

addons:
  apt:
    update: true